[翻译-2020-09-02] DevOps 的打开方式: 构建和部署
jenkins-zh/jenkins-zh pull request #324
Opened 2020-08-17 07:44 UTC by 0N0thing

### 投稿
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 我同意本文首次在 Jenkins 官方微信公众号（Jenkins-Community）上发布

### 原创
- [ ] 我申明当前 PR 中的文章是由我本人创作

### 翻译
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 对应的任务 close #321 

### 维护
- [ ] 维护

2020-08-27 01:13 UTC, LinuxSuRen approved these changes

2020-09-01 00:16 UTC, yJunS requested changes

2020-09-01 00:16 UTC, yJunS commented on content/wechat/articles/2020/09/2020-09-02-devops-adoption-approach-build-and-deploy.md
> +descritpion: 介绍了一下 Jenkins X 的组成部分通过具体的实践告诉读者正确打开在 Kubernetes 上实现 CI/CD 的方式
`descritpion` 拼错了，应该 `description`，并且后面的内容应该用引号引起来，否则在渲染的时候，格式显示会有些问题，`title`后的内容也建议加上引号，header部分应该把 `poster` 加上([示例](https://github.com/jenkins-infra/wechat/blob/master/articles/sample.md))

2020-09-01 01:13 UTC, 0N0thing commented on content/wechat/articles/2020/09/2020-09-02-devops-adoption-approach-build-and-deploy.md
> +descritpion: 介绍了一下 Jenkins X 的组成部分通过具体的实践告诉读者正确打开在 Kubernetes 上实现 CI/CD 的方式
这个[示例](url)我这边看标题格式没有做说明，我这边把 `title` 跟 `description` 加上了，至于那个 `poster` 部分我这边不清楚需要加在哪里。引号我用的中文的引号引起来的。

2020-09-01 03:57 UTC, yJunS commented on content/wechat/articles/2020/09/2020-09-02-devops-adoption-approach-build-and-deploy.md
> +descritpion: 介绍了一下 Jenkins X 的组成部分通过具体的实践告诉读者正确打开在 Kubernetes 上实现 CI/CD 的方式
引号最好还是用半角的引号好一些，`poster` 就是封面图片，跟 `title` 和 `description` 同一级就行

2020-09-01 05:18 UTC, 0N0thing commented on content/wechat/articles/2020/09/2020-09-02-devops-adoption-approach-build-and-deploy.md
> +descritpion: 介绍了一下 Jenkins X 的组成部分通过具体的实践告诉读者正确打开在 Kubernetes 上实现 CI/CD 的方式
> 引号最好还是用半角的引号好一些，`poster` 就是封面图片，跟 `title` 和 `description` 同一级就行

`poster: cover.jpg` 我这样加的，引号问题我改好了，很长时间没有加 poster了，之前提交的就有少这个的情况

2020-09-01 15:44 UTC, yJunS approved these changes

2020-09-01 15:45 UTC, merged

2020-09-02 02:14 UTC, yJunS commented
@0N0thing cover.png不是一个固定格式，是需要自己找一个封面图片，并放进来