[原创-08-08]Jenkins Json Build
jenkins-zh/jenkins-zh pull request #326
Opened 2020-08-25 05:52 UTC by sunweisheng

### 投稿
- [x] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [x] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [x] 我同意本文首次在 Jenkins 官方微信公众号（Jenkins-Community）上发布

### 原创
- [x] 我申明当前 PR 中的文章是由我本人创作

### 翻译
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)

- [ ] 对应的任务 close #

### 维护
- [ ] 维护

2020-08-27 00:33 UTC, LinuxSuRen requested changes
非常感谢投稿。内容写的很详细，不过，从一个读者的角度来看，能耐心地全部阅读完是非常不容易的。从你的文章来看，应该是要介绍一个开源项目。因此，我建议，只要能用简洁的语言把项目的如下信息表达出来即可：

- 发起项目的背景
- 项目当前解决了的问题
- 项目希望能解决的问题
- 一个简单的示例用法
- 欢迎大家去关注、交流等

非常期望共同给出一个读者喜爱的文章，有任何问题，欢迎留言补充。

2020-08-27 00:33 UTC, LinuxSuRen commented on content/wechat/articles/2020/08/2020-08-03-jenkins-json-build.md
> +author: sunweisheng@live.cn
这里应该是GitHub的ID，也就是sunweisheng

2020-08-27 00:33 UTC, LinuxSuRen commented on content/wechat/articles/2020/08/2020-08-03-jenkins-json-build.md
> +date: 2020-08-25
这里的日期，以及文件夹的日期应该是要发布的日期。review并且修改完成的话，估计要到九月初了

2020-08-27 05:47 UTC, sunweisheng commented
好的 谢谢你的建议，我再修改一版。

2020-08-29 13:07 UTC, yJunS requested changes
文件夹和文件名也要对应更改的，

2020-08-31 02:15 UTC, sunweisheng commented
> 文件夹和文件名也要对应更改的，

1

2020-09-06 12:58 UTC, sunweisheng reviewed
我有修改了一版，请审核

2020-09-07 02:30 UTC, LinuxSuRen commented on content/wechat/articles/2020/09/2020-09-11-jenkins-json-build.md
> +title: "Jenkins Json Build"
从标题上，读者很难快速了解到文章到主题、内容，下面给出一些参考：

- 对 Jenkinsfile 语法说不，开源项目 Jenkins Json Build 挺你

2020-09-07 02:45 UTC, sunweisheng reviewed
多谢帮我给文章起了个非常好的名字

2020-09-07 03:06 UTC, LinuxSuRen approved these changes

2020-09-07 03:06 UTC, sunweisheng reviewed
已经将时间改为今天

2020-09-07 03:07 UTC, merged