[翻译-2020-09-02] 使用 Jenkins 和 Ansible 实现 CI/CD
jenkins-zh/jenkins-zh pull request #327
Opened 2020-08-27 02:57 UTC by wwjgit

### 投稿
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 我同意本文首次在 Jenkins 官方微信公众号（Jenkins-Community）上发布

### 原创
- [ ] 我申明当前 PR 中的文章是由我本人创作

### 翻译
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)

- [ ] 对应的任务 close #222

### 维护
- [ ] 维护

2020-09-02 01:45 UTC, yJunS requested changes

2020-09-02 01:45 UTC, yJunS commented on content/wechat/articles/2020/09/2020-09-09-ci-cd-with-jenkins-and-ansible.md
> +我阅读了很多非常不错的文章，介绍如何使用一些单页面  Javascript 和 Spring Boot 后端构建应用，其中还涉及了配置管理，基础框架，持续集成和持续交付。现在我将结合以上所有内容，为你开展自己的工作提供一些支持和帮助。
- `使用一些单页面  Javascript 和 Spring Boot 后端构建应用`这块翻译好像不太准确，大体意思应该是`使用 Javascript 应用程序构建 Spring Boot 后端应用`
- `其中还涉及了配置管理，基础框架，持续集成` 之间应该用顿号间隔。

2020-09-02 01:45 UTC, yJunS commented on content/wechat/articles/2020/09/2020-09-09-ci-cd-with-jenkins-and-ansible.md
> +description: 以一个 Spring Boot + JS 的项目为例，讲解了如何通过 Jenkins 以及 Ansible 实现 CI/CD
`title` 和 `description` 的内容都最好以半角的引号引起来
加一下`poster`（封面）,跟`title`同级

2020-09-02 08:49 UTC, wwjgit commented on content/wechat/articles/2020/09/2020-09-09-ci-cd-with-jenkins-and-ansible.md
> +我阅读了很多非常不错的文章，介绍如何使用一些单页面  Javascript 和 Spring Boot 后端构建应用，其中还涉及了配置管理，基础框架，持续集成和持续交付。现在我将结合以上所有内容，为你开展自己的工作提供一些支持和帮助。
第一点我理解 Javascript 是前端，而且是单页面这种形式的前端。后端是 Spring Boot。前端和后端共同组成了应用。with在这里的更像是“和...一起”，而不是“使用”？理解有误的话，还请指正。    
第二点已修改。

2020-09-02 08:49 UTC, wwjgit commented on content/wechat/articles/2020/09/2020-09-09-ci-cd-with-jenkins-and-ansible.md
> +description: 以一个 Spring Boot + JS 的项目为例，讲解了如何通过 Jenkins 以及 Ansible 实现 CI/CD
已修改

2020-09-08 01:13 UTC, yJunS approved these changes

2020-09-09 02:40 UTC, merged