[翻译-2020-11-04] 使用 AWS、k3s、Rancher、Vault 和 ArgoCD 在 Kubernetes 上集成 GitOps
jenkins-zh/jenkins-zh pull request #384
Opened 2020-11-02 01:35 UTC by 0N0thing

### 投稿
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 我同意本文首次在 Jenkins 官方微信公众号（Jenkins-Community）上发布

### 原创
- [ ] 我申明当前 PR 中的文章是由我本人创作
- [ ] 我同意采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。

### 翻译
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://adam-toy.medium.com/implementing-gitops-on-kubernetes-using-k3s-rancher-vault-and-argocd-f8e770297d3a)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)
- [x] 对应的任务 close #377 

### 维护
- [ ] 维护

2020-11-04 02:07 UTC, yJunS approved these changes

2020-11-04 02:12 UTC, yJunS requested changes
`description` 的内容需要加下引号

2020-11-05 05:38 UTC, 0N0thing commented
> `description` 的内容需要加下引号

👌

2020-11-05 09:41 UTC, LinuxSuRen approved these changes

2020-11-05 09:41 UTC, merged