[翻译-2020-02-21] Jenkins 贡献者线上会议 - 二月 23 日至 25 日
jenkins-zh/jenkins-zh pull request #426
Opened 2021-02-18 03:29 UTC by 0N0thing

### 投稿
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 我同意本文首次在 Jenkins 官方微信公众号（Jenkins-Community）上发布

### 原创
- [ ] 我申明当前 PR 中的文章是由我本人创作
- [ ] 我同意采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。

### 翻译
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://www.jenkins.io/blog/2021/02/16/contributor-summit-online/)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)

- [ ] 对应的任务 close #

### 维护
- [ ] 维护

2021-02-18 05:42 UTC, LinuxSuRen requested changes
我留了几个修改建议，例如：`summit` 经常翻译为“峰会“

2021-02-18 05:42 UTC, LinuxSuRen commented on content/wechat/articles/2021/02/2021-02-26-jenkins-contributor-summit-online-feb-23-25.md
> +Jenkins 贡献者会议让 Jenkins 项目目前以及将来的贡献者们能够齐聚一堂。今年我们主持本次线上会议是为了鼓励全世界的贡献者们相互了解、讨论、规划未来。
这里加个限定语比较合适，例如：讨论、规划 Jenkins 社区的未来发展

2021-02-18 05:42 UTC, LinuxSuRen commented on content/wechat/articles/2021/02/2021-02-26-jenkins-contributor-summit-online-feb-23-25.md
> +开幕式将于 2021 年 2 月 23 日 15 时（北京时间 23 时）开始。在欢迎环节与回顾环节结束后，我们将会听取 Jenkins 项目的负责人介绍过去一年的成果以及未来一年的展望。
其实，这里不太算是 Jenkins 项目的负责人，建议翻译为：Jenkins 社区各个领域的负责人

2021-02-18 05:42 UTC, LinuxSuRen commented on content/wechat/articles/2021/02/2021-02-26-jenkins-contributor-summit-online-feb-23-25.md
> +- 发布 - Tim Jacomb
只是“发布”的话，感觉有点困惑。建议翻译为：“版本发布”

2021-02-18 05:42 UTC, LinuxSuRen commented
/kind translation

2021-02-18 08:20 UTC, 0N0thing commented on content/wechat/articles/2021/02/2021-02-26-jenkins-contributor-summit-online-feb-23-25.md
> +开幕式将于 2021 年 2 月 23 日 15 时（北京时间 23 时）开始。在欢迎环节与回顾环节结束后，我们将会听取 Jenkins 项目的负责人介绍过去一年的成果以及未来一年的展望。
> 其实，这里不太算是 Jenkins 项目的负责人，建议翻译为：Jenkins 社区各个领域的负责人

这里我翻译为“各个项目”了

2021-02-18 08:31 UTC, LinuxSuRen commented
/lgtm

2021-02-18 14:54 UTC, yJunS commented
/LGTM

2021-02-18 14:55 UTC, yJunS commented
/APPROVE

2021-02-18 14:56 UTC, yJunS approved these changes

2021-02-19 00:57 UTC, LinuxSuRen commented
/approve

2021-02-19 00:57 UTC, LinuxSuRen commented
> /APPROVE

得是小写字母

2021-02-19 01:08 UTC, merged