[翻译-2020-03-24] 2020 Google 编程之夏活动总结
jenkins-zh/jenkins-zh pull request #432
Opened 2021-03-22 08:52 UTC by 0N0thing

### 投稿
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 我同意本文首次在 Jenkins 官方微信公众号（Jenkins-Community）上发布

### 原创
- [ ] 我申明当前 PR 中的文章是由我本人创作
- [ ] 我同意采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。

### 翻译
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://www.jenkins.io/blog/2020/12/22/gsoc-report/)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)

- [ ] 对应的任务 close #

### 维护
- [ ] 维护

2021-03-23 14:51 UTC, yJunS requested changes

2021-03-23 14:51 UTC, yJunS commented on content/wechat/articles/2021/03/2021-03-24-google-summer-of-code-2020-summary.md
> +description: 回顾了 GSoC 2020 活动情况，总结过去，展望未来
描述如果不加引号，渲染时候样式会乱掉

2021-03-25 01:36 UTC, LinuxSuRen commented
非常感谢，辛苦了

2021-03-25 01:36 UTC, LinuxSuRen commented
/lgtm

2021-03-25 01:36 UTC, LinuxSuRen commented
/approve

2021-03-25 01:42 UTC, LinuxSuRen commented
/kind translation

2021-03-26 06:12 UTC, merged