Update star-plan.md
jenkins-zh/jenkins-zh pull request #441
Opened 2021-04-21 00:28 UTC by wst021

Modify 2021年 第一期图书激励征集提名人员名单

### 投稿
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 我同意本文首次在 Jenkins 官方微信公众号（Jenkins-Community）上发布

### 原创
- [ ] 我申明当前 PR 中的文章是由我本人创作
- [ ] 我同意采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。

### 翻译
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)

- [ ] 对应的任务 close #

### 维护
- [ ] 维护

2021-04-21 00:31 UTC, wst021 commented
commit Modify 2021年 第一期图书激励征集提名人员名单

2021-04-21 00:37 UTC, LinuxSuRen requested changes
感谢帮忙收集贡献者的信息，但是，有些地方需要做个修改

2021-04-21 00:37 UTC, LinuxSuRen commented on content/about/star-plan.md
> +### NO.1
这个不是第一期，应该是第六期了

2021-04-21 00:37 UTC, LinuxSuRen commented on content/about/star-plan.md
> +时间范围：2021年1月～2021年4月
日期应该是从2020年12月开始的

2021-04-21 00:37 UTC, LinuxSuRen commented
/kind chroe

2021-04-21 01:17 UTC, wst021 commented on content/about/star-plan.md
> +### NO.1
啊，是第六期，接着上期是吧？  我以为按年算，新的一年第一期开始。

2021-04-21 01:18 UTC, LinuxSuRen commented on content/about/star-plan.md
> +时间范围：2021年1月～2021年4月
我们的激励不是非常频繁，按照年记的话，价值不大。

2021-04-21 01:22 UTC, wst021 commented on content/about/star-plan.md
> +时间范围：2021年1月～2021年4月
OK ，已经都修改了，你再看看。

2021-04-21 01:27 UTC, LinuxSuRen approved these changes

2021-04-22 07:13 UTC, LinuxSuRen commented
/kind chore

2021-05-05 10:31 UTC, yJunS approved these changes

2021-05-05 10:39 UTC, merged

2021-05-05 11:06 UTC, LinuxSuRen commented
我还没有收到图书，本来是想等确认收到后再合并的。我再问问出版社

2021-05-08 08:10 UTC, yJunS commented
额。我也还没收到。 这次时间确实有点久