Configure Plugins with JCasC tutorial translation
jenkins-zh/jenkins-zh pull request #454
Opened 2021-07-01 03:08 UTC by jxr98

### 投稿
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 我同意本文首次在 Jenkins 官方微信公众号（Jenkins-Community）上发布

### 原创
- [ ] 我申明当前 PR 中的文章是由我本人创作
- [ ] 我同意采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。

### 翻译
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)

- [ ] 对应的任务 close #

### 维护
- [ ] 维护

2021-07-01 04:02 UTC, yJunS commented
请按规范将描述打勾，谢谢

2021-07-01 12:34 UTC, yJunS reviewed
这个文件要在网站哪里显示？  没看明白

2021-07-01 13:02 UTC, jxr98 commented
这个是issue里的一个翻译。https://github.com/jenkins-zh/jenkins-zh/issues/453
我把翻译后的文章放在最外面了，不知道要放到哪个文件夹里。

2021-07-01 13:23 UTC, yJunS commented
![image](https://user-images.githubusercontent.com/20575981/124131576-87a98600-dab2-11eb-9d0b-a90e8c1e27be.png)
有文章发布规则和格式要求，按照要求改一下吧

2021-07-01 13:25 UTC, yJunS commented
[目录](https://github.com/jenkins-zh/jenkins-zh/tree/master/content/wechat/articles/2021) 参照这个里面的文章

2021-07-04 03:08 UTC, LinuxSuRen requested changes
你需要按照指定的格式来提交

![image](https://user-images.githubusercontent.com/1450685/124371827-2f43d580-dcb8-11eb-82a5-ba15a320ac2a.png)

https://github.com/jenkins-infra/wechat/blob/master/articles/sample.md

2021-07-04 03:09 UTC, LinuxSuRen commented on 用JCasC配置插件.md
> +# 用JCasC配置插件
这个文件是不需要提交的

2021-07-07 13:24 UTC, yJunS requested changes

2021-07-07 13:24 UTC, yJunS commented on content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation.md
> +description: 一个用JCasC配置插件的教程，主要是用yaml文件来配置插件，教程简单，大致分为六个步骤。
这类字符串的用引号引起来，否则格式会错乱

2021-07-07 13:24 UTC, yJunS commented on content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation.md
> +date: 2021-07-04
发布日期需要和文件的日期一致，且需要预留审批时间

2021-07-07 13:24 UTC, yJunS commented on content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation.md
> +- tag1 jenkins
`tag` 里不需要 tag1、tag2 这类的

2021-07-07 13:24 UTC, yJunS commented on content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation.md
> +[GitHub](https://github.com/dheerajodha)    [LinkedIn](https://www.linkedin.com/in/dheeraj-singh-jodha)
这段在文章里应该不需要翻译的

2021-07-11 08:16 UTC, jxr98 commented on content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation.md
> +[GitHub](https://github.com/dheerajodha)    [LinkedIn](https://www.linkedin.com/in/dheeraj-singh-jodha)
好了。

2021-07-15 06:31 UTC, merged