议题公开征集
jenkins-zh/jenkins-zh pull request #456
Opened 2021-07-15 09:49 UTC by LinuxSuRen

### 投稿
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 我同意本文首次在 Jenkins 官方微信公众号（Jenkins-Community）上发布

### 原创
- [ ] 我申明当前 PR 中的文章是由我本人创作
- [ ] 我同意采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。

### 翻译
- [ ] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://jenkins-zh.cn/)
    - [ ] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)

- [ ] 对应的任务 close #

### 维护
- [ ] 维护

2021-07-16 09:37 UTC, yJunS requested changes

2021-07-16 09:37 UTC, yJunS commented on content/wechat/articles/2021/07/2091-07-19-call-for-paper.md
> +您可以通过发送邮件到 admin@jenkins-zh.cn，或者直接提交 issue 到 GitHub https://github.com/jenkins-zh/jenkins-zh/issues/new
发至 admins@jenkins-zh.cn ？

2021-07-16 09:37 UTC, yJunS commented on content/wechat/articles/2021/07/2091-07-19-call-for-paper.md
> +* 我对 Jenkins 的了解不多，使用时间也不是很旧，还可以分享吗？
很旧 -> 很久

2021-07-16 09:49 UTC, LinuxSuRen commented on content/wechat/articles/2021/07/2091-07-19-call-for-paper.md
> +您可以通过发送邮件到 admin@jenkins-zh.cn，或者直接提交 issue 到 GitHub https://github.com/jenkins-zh/jenkins-zh/issues/new
那是不是 
![image](https://user-images.githubusercontent.com/1450685/125928790-6ff5092c-20fc-44df-ae6f-05fc7ae362f6.png)
 这里的地址也是错的

2021-07-19 06:34 UTC, LinuxSuRen commented on content/wechat/articles/2021/07/2091-07-19-call-for-paper.md
> +您可以通过发送邮件到 admin@jenkins-zh.cn，或者直接提交 issue 到 GitHub https://github.com/jenkins-zh/jenkins-zh/issues/new
邮箱没有错误，`s` 结尾的邮箱是邮箱组

2021-07-19 06:35 UTC, merged