[翻译-2021-08-04] 在 Jenkins 上轻松重用 Tekton 和 Jenkins X
jenkins-zh/jenkins-zh pull request #457
Opened 2021-08-01 09:17 UTC by 0N0thing

### 投稿
- [ ] 我已阅读[文章发布规则](https://github.com/jenkins-infra/wechat/tree/master/management/operators/README.md)
- [ ] 我已阅读[文章编写格式](https://github.com/jenkins-infra/wechat/tree/master/articles/README.md)
- [ ] 我同意本文首次在 Jenkins 官方微信公众号（Jenkins-Community）上发布

### 原创
- [ ] 我申明当前 PR 中的文章是由我本人创作
- [ ] 我同意采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。

### 翻译
- [x] 翻译，为了方便大家 Review，我已经把原文地址拷贝到了[这里](https://www.jenkins.io/blog/2021/04/21/tekton-plugin/)
    - [x] 我已阅读[翻译规范](https://github.com/jenkins-zh/translation-spec)

- [x] 对应的任务 close #442 

### 维护
- [ ] 维护

2021-08-02 01:21 UTC, LinuxSuRen commented
投稿规则那块，记得阅读并勾选下

2021-08-02 01:23 UTC, 0N0thing commented
> 投稿规则那块，记得阅读并勾选下

已勾选 ✔️

2021-08-03 00:31 UTC, yJunS requested changes
![image](https://user-images.githubusercontent.com/20575981/127939653-af0b4578-be59-42ee-aa8e-82e5a4904c34.png)
请按实际对应文件夹创建对应文件夹

2021-08-04 01:22 UTC, 0N0thing commented
> ![image](https://user-images.githubusercontent.com/20575981/127939653-af0b4578-be59-42ee-aa8e-82e5a4904c34.png)
> 请按实际对应文件夹创建对应文件夹

已修改完成，长时间没有更新了，忘记了 😄

2021-08-04 15:28 UTC, yJunS approved these changes
LGTM

2021-08-05 05:43 UTC, LinuxSuRen approved these changes

2021-08-05 05:43 UTC, merged